### ISSUE TITLE
Problems With System.launch3DSX function.

### ISSUE THREAD

**Issue by The-Sparrow** [Rinnegatamante/lpp-3ds#17] opened 2016-01-31 23:08 UTC
Whenever i try to load a .3DSX through lpp-3ds it comes out with two black screens.
I was just trying something out this morning and ran into this issue.
Help would greatly be appreciated!

**Comment by ihaveamac** [comment] 2016-01-31 23:09
what are you trying to launch with it?

**Comment by Rinnegatamante** [comment] 2016-01-31 23:26
What's your system? Does the 3DSX have a descriptor? (XML file)

**Comment by The-Sparrow** [comment] 2016-01-31 23:31
Im trying to run a seperate lpp-3ds 3dsx i wrote, It just says Test.
No theres not an XML descriptor, and im on 9.2 O3DS

**Comment by Rinnegatamante** [comment] 2016-01-31 23:34
Is the 3DSX lua script dependent? If so, try to put it in SD root.

**Comment by The-Sparrow** [comment] 2016-01-31 23:38
Yes, the 3DSX needs the lua script to run.
Ok i'll try it now

**Comment by The-Sparrow** [comment] 2016-01-31 23:43
Nope, still two black screens :( @Rinnegatamante

**Comment by Rinnegatamante** [comment] 2016-01-31 23:46
Try to use the same function with a self-dependent 3DSX which doesn't need also an XML file to see if the problem is in launch3DSX itself.

**Comment by The-Sparrow** [comment] 2016-01-31 23:49
@Rinnegatamante  I think the problem is within launch3DSX , because i tried it with a .3dsx file that didnt use an XML file, and got the same result.

**Comment by Rinnegatamante** [comment] 2016-01-31 23:51
Are you using official R4 version?

**Comment by ihaveamac** [comment] 2016-01-31 23:51
a34b5bfcdf8a119b1aff94dfb273f423f659e933 was committed *after* the release of r4, so the one in r4 is broken.

**Comment by The-Sparrow** [comment] 2016-02-01 01:37
@Rinnegatamante  Yes, i am

**Comment by ihaveamac** [comment] 2016-02-01 01:39
I noticed that after mentioning the commit above that a new nightly was uploaded. maybe you could try it out? https://github.com/Rinnegatamante/lpp-3ds/blob/master/bin/lpp-3ds.3dsx

**Comment by ihaveamac** [comment] 2016-02-01 01:41
basically, `System.launch3DSX()` does not work (on *hax 2.5) in r4. this was fixed later on though (a34b5bfcdf8a119b1aff94dfb273f423f659e933) and will end up in r5.

**Comment by Rinnegatamante** [comment] 2016-02-02 13:03
As @ihaveamac said, use the Nightly Build i recently uploaded. It should solve the problem.

**Closed by Rinnegatamante** 2016-02-02 13:03 UTC
